apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "frontend.name" . }}-config"
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
    SERVICE_API1_ENDPOINT: /api
    PORT: "3000"