apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "api-1.name" . }}-config"
  labels:
    {{- include "api-1.labels" . | nindent 4 }}
data:
    SERVICE_API2_ENDPOINT: http://backend-api-2-svc.api2/api
    PORT: "3010"